# Generated by Django 5.0.3 on 2024-03-11 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textextraction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extractedtext',
            name='parameter',
        ),
        migrations.RemoveField(
            model_name='extractedtext',
            name='value',
        ),
        migrations.AddField(
            model_name='extractedtext',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
